name: Run ADO to GitHub Sync with PowerShell

on:
  worflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2
      - run: |
          ./SynADOtoGitHub.pl1 -GitHubDestination ${{ secrets.GITHUBDESTINATIONPAT }} -ADOSourcePAT ${{ secrets.ADOSOURCEPAT}}
      
